name: Runbox-SearchIndex

on: [push, pull_request]

jobs:
    build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v1
          with:
            node-version: '16.x'
        - uses: actions/setup-python@v5
          with:
            python-version: '3.9'
        - run: ./setup-emsdh.sh
        - run: source ./emsdk/emsdk_env.sh
        - run: ./build-xapian.sh
        - run: npm ci
        - run: npm run test-no-watch

